Trabalho_8_devWeb/Site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'Site'


urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('noticia/', views.noticia, name='noticia'),
    path('login/', views.login, name='login'),
    path('cadastrar/', views.cadastra_User, name='cadastra_User'),
    path('exibirUser/<int:id>/', views.exibe_user, name='exibe_user'),
    path('editar/<int:id>/', views.edita_user, name='edita_user'),
    path('remover/', views.remove_user, name='remove_user'),

    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('remove_produto/', views.remove_produto, name='remove_produto'),
    path('atualiza_produto/', views.atualiza_produto, name='atualiza_produto'),
    path('listar_produto/', views.lista_produtos, name='lista_produtos'),
    path('exibir/<int:id>/', views.exibe_produto, name='exibe_produto'),

    path('SalvaprodutoCarrinho/', views.SalvaprodutoCarrinho, name='SalvaprodutoCarrinho'),
    path('RemoveprodutoCarrinho/', views.RemoveprodutoCarrinho, name='RemoveprodutoCarrinho'),

    path('Carrinho/',views.ListaCarrinho,name='ListaCarrinho'),
]

Trabalho_8_devWeb/Trabalho_5_devWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Site.urls')),
    path('Site/', include('Site.urls')),
    path('autenticacao/', include('autenticacao.urls')),
]

Trabalho_8_devWeb/Site/models.py
from django.conf import settings
from django.db import models

class Images(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, db_index=True)
    caminho = models.CharField(max_length=200, db_index=True)

    class Meta:
        db_table = 'images'
        ordering = ('id',)

    def __str__(self):
        return self.nome

class User(models.Model):
    nome = models.CharField(max_length=120)
    email = models.CharField(max_length=120)
    cpf = models.CharField(max_length=20)
    endereco = models.CharField(max_length=20)
    data_cadastro = models.DateField(null=True)


    class Meta:
        db_table = 'User'
        ordering = ('nome',)

    def __str__(self):
        return self.nome

    def data_cadastro_masc(self):
        return self.data_cadastro.strftime("%d/%m/%Y")



class Categoria(models.Model):
    nome = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200)

    class Meta:
        db_table = 'categoria'

    def __str__(self):
        return self.nome

class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=120)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    estoque = models.PositiveIntegerField(default=0)
    disponivel = models.BooleanField(default=True)
    data_de_cadastro = models.DateField(null=True)

    class Meta:
        db_table = 'produto'

    def __str__(self):
        return self.nome

    def data_cadastro_masc(self):
        return self.data_de_cadastro.strftime("%d/%m/%Y")

Trabalho_8_devWeb/templates/Cadastro/cadastra_user.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Pagina principal
{% endblock %}

{% block conteudo %}
<br/>
    <div class="row">
        <div class="col-12">
            <h4 class="titulo mb-0">Cadastro de Usuários</h4>
            <hr class="mt-2 mb-4">
        </div>
    </div>
    <form id="formulario" action ="{% url 'Site:cadastra_User' %}" method ="POST" novalidate>
        <div class="form-group row" style="margin-bottom: 10px;" hidden>
            <label for="id" class="col-lg-2 col-form-label font-weight-bold">id</label>
            <div class="col-lg-10">
                {{ form.id }}
                {% if form.id.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.id.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    {# <input type="hidden" name="User_id" id="id_User_id" value="xxx"> #}

        <div class="form-group row" style="margin-bottom: 10px;">
            <label for="id_nome" class="col-lg-2 col-form-label font-weight-bold">Nome</label>
            <div class="col-lg-10">
                {{ form.nome }}
                {% if form.nome.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.nome.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        {#  <input type="text"                               #}
        {#     name="nome"                                   #}
        {#     id="id_nome"                                  #}
        {#     class="form-control form-control-sm"          #}
        {#     maxlength="50"                                #}
        {#     required>                                     #}



        <div class="form-group row" style="margin-bottom: 10px;">
            <label for="id_email" class="col-lg-2 col-form-label font-weight-bold">Email</label>
            <div class="col-lg-10">
                {{ form.email }}
                {% if form.email.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.email.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        {#  <input type="text"                               #}
        {#     name="email"                                  #}
        {#     id="id_email"                                 #}
        {#     class="form-control form-control-sm"          #}
        {#     maxlength="50"                                #}
        {#     required>                                     #}

        <div class="form-group row" style="margin-bottom: 10px;">
            <label for="id_cpf" class="col-lg-2 col-form-label font-weight-bold">CPF</label>
            <div class="col-lg-10">
                {{ form.cpf }}
                {% if form.cpf.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.cpf.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        {#  <input type="text"                               #}
        {#     name="cpf"                                    #}
        {#     id="id_cpf"                                   #}
        {#     class="form-control form-control-sm"          #}
        {#     maxlength="50"                                #}
        {#     required>                                     #}



        <div class="form-group row" style="margin-bottom: 10px;">
            <label for="id_endereco" class="col-lg-2 col-form-label font-weight-bold">Endereco</label>
            <div class="col-lg-10">
                {{ form.endereco }}
                {% if form.endereco.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.endereco.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        {#  <input type="text"                               #}
        {#     name="endereco"                                #}
        {#     id="id_endereco"                               #}
        {#     class="form-control form-control-sm"          #}
        {#     maxlength="50"                                #}
        {#     required>                                     #}



        <div class="form-group row mb-2">
            <label for="id_data_cadastro" class="col-lg-2 col-form-label font-weight-bold">Data de Cadastro</label>
            <div class="col-lg-3">
                {{ form.data_cadastro }}
                {% if form.data_cadastro.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.data_cadastro.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="col-lg-7"></div>
        </div>

        <div class="form-group" style="margin-top: 20px;">
            <div class="row">
                <div class="col-lg-10 offset-lg-2">
                    {% csrf_token %}
                    <button id="botao" type="button" class="btn btn-primary">
                        <img src="{% static caminhos.cadastro_1 %}">
                        {% if acao == 'inclusao' %}
                            Cadastrar User
                        {% else %}
                            Alterar User
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>


{% endblock %}

Trabalho_8_devWeb/templates/Cadastro/exibe_usuario.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Pagina principal
{% endblock %}

{% block conteudo %}
    <br/>
     <div style="margin-bottom: 15px;">
        <div class="text-left">
            <h4 class="titulo" style="margin-bottom: 0px;">Cadastro de Usuario</h4>
            <hr style="margin-top: 10px; margin-bottom: 0px;">
        </div>
    </div>

    {% if messages %}
        <div class="row mb-3">
            <div class="col-12">
                {% for message in messages %}
                    <ul class="list-group rounded border border-{% if message.tags == 'info' %}info{% else %}danger{% endif %}">
                        {# Supondo a utilização de apenas info e danger #}
                        <li style="padding-top: 7px; padding-bottom: 7px;" class="list-group-item list-group-item-{% if message.tags == 'info' %}info{% else %}danger{% endif %}">
                            {{ message }}
                        </li>
                    </ul>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <div class="row">

        <div class="col-lg-2">
            <span class="texto"><b>Nome: </b></span>
        </div>
        <div class="col-lg-10">
            <span class="texto">{{ user.nome }}</span>
        </div>

        <div class="col-lg-2">
            <span class="texto"><b>Email: </b></span>
        </div>
        <div class="col-lg-10">
            <span class="texto">{{ user.email }}</span>
        </div>

        <div class="col-lg-2">
            <span class="texto"><b>CPF: </b></span>
        </div>
        <div class="col-lg-10">
            <span class="texto">{{ user.cpf }}</span>
        </div>

         <div class="col-lg-2">
            <span class="texto"><b>Endereço: </b></span>
        </div>
        <div class="col-lg-10">
            <span class="texto">{{ user.endereco }}</span>
        </div>

        <div class="col-lg-2">
            <span class="texto"><b>Data de cadastro: </b></span>
        </div>
        <div class="col-lg-10">
            <span class="texto">{{ user.data_cadastro_masc }}</span>
        </div>
    </div>

    {% if remove_user_form %}
        <div class="form-group" style="margin-top: 10px; margin-bottom: 0px;">
            <div class="row">
                <div class="col-lg-12 form-inline">
                    <a id="botao_editar" style="margin-right: 15px;" href="{% url 'Site:edita_user' user.id %}" style="margin-top: 0px" class="btn btn-primary">
                        <img src="{% static caminhos.exibir_1 %}"/>
                        Editar
                    </a>
                    &nbsp;
                    <form id="remove_user_form" style="margin-bottom: 0px; margin-top: 0px;" action ="{% url 'Site:remove_user' %}" method ="POST" novalidate>
                        {% csrf_token %}
                        <div class="form-group row" style="margin-bottom: 10px;" hidden>
                            <input type="hidden" name="User_id" id="id_User_id" value="{{ remove_user_form }}">
                        </div>
                        <button id="botao_remover" style="margin-top: 0px;" type="button" class="btn btn-danger">
                            <img src="{% static caminhos.exibir_2 %}"/> Remover
                        </button>
                    </form>

                </div>
            </div>
        </div>
    {% endif %}



{% endblock %}