Trabalho_8_devWeb/Site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'Site'


urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('noticia/', views.noticia, name='noticia'),
    path('login/', views.login, name='login'),
    path('cadastrar/', views.cadastra_User, name='cadastra_User'),
    path('exibirUser/<int:id>/', views.exibe_user, name='exibe_user'),
    path('editar/<int:id>/', views.edita_user, name='edita_user'),
    path('remover/', views.remove_user, name='remove_user'),

    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('remove_produto/', views.remove_produto, name='remove_produto'),
    path('atualiza_produto/', views.atualiza_produto, name='atualiza_produto'),
    path('listar_produto/', views.lista_produtos, name='lista_produtos'),
    path('exibir/<int:id>/', views.exibe_produto, name='exibe_produto'),

    path('SalvaprodutoCarrinho/', views.SalvaprodutoCarrinho, name='SalvaprodutoCarrinho'),
    path('RemoveprodutoCarrinho/', views.RemoveprodutoCarrinho, name='RemoveprodutoCarrinho'),

    path('Carrinho/',views.ListaCarrinho,name='ListaCarrinho'),
]

Trabalho_8_devWeb/Trabalho_5_devWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Site.urls')),
    path('Site/', include('Site.urls')),
    path('autenticacao/', include('autenticacao.urls')),
]

Trabalho_8_devWeb/Site/forms.py
from decimal import Decimal
from django import forms
from django.core.validators import RegexValidator
from Trabalho_5_devWeb import settings
from Site.models import Produto, Categoria
from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('id','nome', 'email', 'cpf', 'endereco', 'data_cadastro')
        # <input type="hidden" name="User_id" id="id_User_id" value="xxx">

    id = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=False)

    # <input type="hidden" name="User_id" id="id_User_id" value="xxx">


    nome = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=True)

    # <input type="text"
    #        name="nome"
    #        id="id_nome"
    #        class="form-control form-control-sm"
    #        maxlength="120"
    #        required>

    email = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),

        required=True)

    # <input type="text"
    #        name="email"
    #        id="id_email"
    #        class="form-control form-control-sm"
    #        maxlength="120"
    #        required>

    cpf = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),

        required=True)

    # <input type="text"
    #        name="cpf"
    #        id="id_cpf"
    #        class="form-control form-control-sm"
    #        maxlength="120"
    #        required>

    endereco = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),

        required=True)

    # <input type="text"
    #        name="endereco"
    #        id="id_endereco"
    #        class="form-control form-control-sm"
    #        maxlength="120"
    #        required>

    # <input type="text"
    #        name="preco"
    #        id="id_preco"
    #        class="form-control form-control-sm"
    #        min_length="4"
    #        maxlength="10"
    #        onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44')
    #        required>

    data_cadastro = forms.DateField(
        input_formats = settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(attrs={'class': 'form-control form-control-sm'}),
        required=True)

    # <input type="text"
    #        name="data_cadastro"
    #        class="form-control form-control-sm hasDatepicker"
    #        required=""
    #        id="id_data_cadastro"
    #        maxlength="10">

class RemoveUserForm(forms.Form):
    class Meta:
        fields = ('id')

    id = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=False)
    # <input type="hidden" name="User_id" id="id_User_id" value="xxx">

class AtualizaProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        # O campo fields abaixo impede que seja atualizado um campo não especificado na lista abaixo. Deve ser especificado o
        # campo fields ou o campo exclude.
        fields = ('produto_id', 'estoque')

    produto_id = forms.CharField(widget=forms.HiddenInput(), required=True)

    estoque = forms.IntegerField(
        min_value=1,
        max_value=1000,
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm estoque',
                                      'maxlength': '20',
                                      'onkeypress': 'return event.charCode >= 48 && event.charCode <= 57'}),
        required=True)

class PesquisaProdutoForm(forms.Form):
    class Meta:
        fields = ('buscaPor')

    buscaPor = forms.CharField(
        max_length=120,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
        required=False)

class ProdutoForm(forms.ModelForm):

    error_messages = {
        'campo_invalido': "Valor de estoque inválido.",
        'estoque_invalido': "O estoque deve ser > zero.",
    }

    class Meta:
        model = Produto
        # O campo fields abaixo impede que seja atualizado um campo não especificado na lista abaixo. Deve ser especificado o
        # campo fields ou o campo exclude.
        fields = ('produto_id', 'categoria', 'nome', 'preco', 'estoque', 'disponivel', 'data_de_cadastro')

    produto_id = forms.CharField(widget=forms.HiddenInput(), required=False)

    categoria = forms.ModelChoiceField(
        error_messages={'required': 'Campo obrigatório.', },
        queryset=Categoria.objects.all().order_by('nome'),
        empty_label='--- Selecione a Categoria ---',
        widget=forms.Select(attrs={'class': 'form-control form-control-sm'}),
        required=True)

    nome = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '120'}),
        required=True)

    preco = forms.CharField(
        error_messages={'required': 'Campo obrigatório.', },
        min_length=4, validators=[
            RegexValidator(regex='^[0-9]{1,7}(,[0-9]{2})?$', message="Informe o preço no formato 9999999,99.")],
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm',
                                      'maxlength': '10',
                                      'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'}),
        required=True)

    estoque = forms.IntegerField(
        min_value=0,
        max_value=1000,
        error_messages={'required': 'Campo obrigatório.', },
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm',
                                      'maxlength': '20',
                                      'onkeypress': 'return event.charCode >= 48 && event.charCode <= 57'}),
        required=True)

    data_de_cadastro = forms.DateField(
        input_formats=settings.DATE_INPUT_FORMATS,
        widget=forms.DateInput(attrs={'class': 'form-control form-control-sm'}),
        required=True)

    # disponivel = forms.BooleanField(
    #     widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    #     required=False)

    disponivel = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'class': 'custom-control-input'}),
        required=False)

    def clean_preco(self):
        preco = self.cleaned_data.get('preco')

        preco = Decimal(preco.replace(',', '.'))

        return preco

    def clean_estoque(self):
        estoque = self.cleaned_data.get('estoque')

        if not estoque:
            return estoque

        if estoque > 900:
            raise forms.ValidationError(
                self.error_messages['campo_invalido'], code='campo_invalido',
            )
        return estoque

    def clean(self):
        estoque = self.cleaned_data.get('estoque')
        disponivel = self.cleaned_data.get('disponivel')

        if disponivel and estoque == 0:
            self.add_error('estoque', "Como o produto está disponível, o estoque deve ser > zero.")
            # raise forms.ValidationError(self.error_messages['estoque_invalido'], code='estoque_invalido'})

        return self.cleaned_data

class RemoveProdutoForm(forms.Form):
    class Meta:
        fields = ('produto_id' )

    produto_id = forms.CharField(widget=forms.HiddenInput())

class ColocaProdutoCarrinhoForm(forms.Form):
    class Meta:
        fields = ('produto_id','produto_qtd')

    produto_id = forms.CharField(widget=forms.HiddenInput())
    produto_qtd = forms.IntegerField(widget=forms.HiddenInput())

Trabalho_8_devWeb/templates/produto/cadastra_produto.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Cadastro de Produtos
{% endblock %}

{% block estilo %}

{% endblock %}

{% block conteudo %}
    <br>
    <div class="row">
        <div class="col-lg-12">
            <h4 class="titulo mb-0">Cadastro de Produtos</h4>
            <hr class="mt-2 mb-4">
        </div>
    </div>

    <form id="inclusao" action ="{% url 'Site:cadastra_produto' %}" method ="POST" novalidate>

        <div class="form-group row mb-2">
            <label for="id_categoria" class="col-lg-2 col-form-label font-weight-bold">Categoria</label>
            <div class="col-lg-10">
                {{ form.categoria }}
        {#      <select name="categoria" class="form-control form-control-sm" required="" id="id_categoria">   #}
        {#          <option value="" selected="">--- Selecione uma categoria ---</option>                      #}
        {#          <option value="1">Eletrodoméstico</option>                                                 #}
        {#          <option value="2">Celular</option>                                                         #}
        {#          <option value="3">Computador</option>                                                      #}
        {#      </select>                                                                                      #}
                {% if form.categoria.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.categoria.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group row mb-2">
            <label for="id_nome" class="col-lg-2 col-form-label font-weight-bold">Nome</label>
            <div class="col-lg-10">
                {{ form.nome }}
        {#      <input type="text" name="nome"                                                            #}
        {#             class="form-control form-control-sm" maxlength="120" required="" id="id_nome">     #}
                {% if form.nome.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.nome.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group row mb-2">
            <label for="id_preco" class="col-lg-2 col-form-label font-weight-bold">Preço</label>
            <div class="col-lg-10">
                {{ form.preco }}
                {% if form.preco.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.preco.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group row mb-2">
            <label for="id_estoque" class="col-lg-2 col-form-label font-weight-bold">Estoque</label>
            <div class="col-lg-10">
                {{ form.estoque }}
                {% if form.estoque.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.estoque.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group row mb-2">
            <div class="col-lg-2"></div>
            <div class="col-lg-10">
                <div class="custom-control custom-checkbox">
                    {{ form.disponivel }}
                    <label class="custom-control-label font-weight-bold" for="id_disponivel">
                        Disponível
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group row mb-2">
            <label for="id_data_de_cadastro" class="col-lg-2 col-form-label font-weight-bold">Data de Cadastro</label>
            <div class="col-lg-3">
                {{ form.data_de_cadastro }}
                {% if form.data_de_cadastro.errors %}
                    <div class="alert alert-danger mb-0" style="padding-top: 2px; padding-bottom: 2px;">
                        {% for error in form.data_de_cadastro.errors %}
                            <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="col-lg-7"></div>
        </div>

        <div class="form-group row" style="margin-top: 20px;">
            <div class="col-lg-10 offset-lg-2">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary"><img src="{% static 'Site/images/skin/database_save.png' %}">
                    Cadastrar Produto
                </button>
            </div>
        </div>

    </form>
    <br>
    <div id="ajax">
        {% include 'produto/lista_de_produtos.html' %}
    </div>
    <br/>
    <br/>
    <br/>
{% endblock %}


{% block domready %}

    $("#id_data_de_cadastro").datepicker({
{#        minDate: new Date(1950, 0, 1),#}
{#        maxDate: new Date({{ ano_atual }}, {{ mes_atual }} - 1, {{ dia_atual }}),#}
        dateFormat: 'dd/mm/yy',
        dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
        dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
        dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
        monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
        monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
        nextText: 'Próximo',
        prevText: 'Anterior',
        showOn: "focus",
    });

    $("#id_data_de_cadastro").mask("00/00/0000");
    var ids_dos_produtos = {{ ids_dos_produtos }}

    $("#inclusao").submit(function(e) {
        e.preventDefault()
        let url = $(this).attr('action')
        let formData = $(this).serializeArray()
        console.log(formData)
        $.post(url, formData, function(resposta) {
            let conteudo = $(resposta).find("#tbody tr:first")
            $("#tabela tbody tr:last").before("<tr style='display: none'>" + $(conteudo).html() + "</tr>")
            $("tr:hidden").fadeIn('slow')
            let total = $(resposta).find("#valor-do-estoque")
            $("#valor-do-estoque").text($(total).text())
            let id = $(conteudo).find("td:first").text()
            id = parseInt(id)
            console.log(ids_dos_produtos)
            ids_dos_produtos.push(id)
            console.log(ids_dos_produtos)
        })
    })

    $("#ajax").on("click", "button.btn-remove", function() {
        let form = $(this).parent();
        let tr = $(form).parent().parent();
        let ind = $(tr).index();
        let valor_id = ids_dos_produtos[ind];
        let input = "<input type='hidden' name='produto_id' value='" + valor_id + "'>";
        $(form).append(input);
        let url = $(form).attr('action')
        let formData = $(form).serializeArray()
        $.post(url, formData, function(resposta) {
            $(tr).fadeTo('slow', 0.3, function() {
                $(tr).remove()
                ids_dos_produtos.splice(ind, 1)
                $("#valor-do-estoque").text(resposta)
            })
        })
    })

    $("#ajax").on("blur", "input.estoque", function() {
        if ($(this).val() <= 0) {
            $(this).focus()
            return
        }
        let form = $(this).parent();
        let tr = $(form).parent().parent();
        let ind = $(tr).index();
        let valor_id = ids_dos_produtos[ind];
        let input = "<input type='hidden' name='produto_id' value='" + valor_id + "'>";
        $(form).append(input);
        let url = $(form).attr('action')
        let formData = $(form).serializeArray()
        $.post(url, formData, function(resposta) {
            $("#valor-do-estoque").text(resposta)
        })
    })

{% endblock %}

Trabalho_8_devWeb/templates/produto/exibe_produto.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Cadastro de Produtos
{% endblock %}

{% block conteudo %}
    <br>
    <div style="margin-bottom: 15px;">
        <div class="text-left">
            <h4 class="titulo" style="margin-bottom: 0px;">Cadastro de Produtos</h4>
            <hr style="margin-top: 10px; margin-bottom: 0px;">
        </div>
    </div>

    {% if messages %}
        <div class="row mb-3">
            <div class="col-12">
                {% for message in messages %}
                    <ul class="list-group rounded border border-{% if message.tags == 'info' %}info{% else %}danger{% endif %}">
                        {# Supondo a utilização de apenas info e danger #}
                        <li style="padding-top: 7px; padding-bottom: 7px;" class="list-group-item list-group-item-{% if message.tags == 'info' %}info{% else %}danger{% endif %}">
                            {{ message }}
                        </li>
                    </ul>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-lg-2">
            <span class="texto"><b>Categoria: </b></span>
        </div>
        <div class="col-lg-10">
            <span class="texto">{{ produto.categoria }}</span>
        </div>

        <div class="col-lg-2">
            <span class="texto"><b>Nome: </b></span>
        </div>
        <div class="col-lg-10">
            <span class="texto">{{ produto.nome }}</span>
        </div>

        <div class="col-lg-2">
            <span class="texto"><b>Preço: </b></span>
        </div>
        <div class="col-lg-10">
            <span class="texto">{{ produto.preco }}</span>
        </div>

        <div class="col-lg-2">
            <span class="texto"><b>Data de cadastro: </b></span>
        </div>
        <div class="col-lg-10">
            <span class="texto">{{ produto.data_cadastro_masc }}</span>
        </div>
    </div>
    {% if remove_produto_form %}
        <div class="form-group" style="margin-top: 10px; margin-bottom: 0px;">
            <div class="row">
                <div class="col-lg-12 form-inline">
                    <a id="botao_editar" style="margin-right: 15px;" href="{% url 'produto:edita_produto' produto.id %}" style="margin-top: 0px" class="btn btn-primary">
                        <img src="{% static 'produto/images/skin/database_edit.png' %}"/>
                        Editar
                    </a>
                    &nbsp;
                    <form id="remove_produto_form"
                          style="margin-bottom: 0px; margin-top: 0px;"
                          action ="{% url 'produto:remove_produto' %}"
                          method ="post" novalidate>
                        {% csrf_token %}

                        <button id="botao_remover" style="margin-top: 0px;" type="button" class="btn btn-danger">
                            <img src="{% static 'produto/images/skin/database_delete.png' %}"/> Remover
                        </button>
                    </form>

                </div>
            </div>
        </div>
    {% endif %}
    
{% endblock %}

{% block domready %}
    $("#botao_remover").click(function() {
        $("#remove_produto_form").append('{{ remove_produto_form.produto_id }}')
        $("#remove_produto_form").submit()
    })
{% endblock %}

Trabalho_8_devWeb/templates/produto/lista_de_produtos.html
{% load static %}

<div class="row">
    <div class="col-12">
        <div class="table-responsive">
            <table id="tabela" style="width:100%" class="table table-striped table-sm table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">Número</th>
                        <th class="text-center">Nome</th>
                        <th class="text-center">Preço</th>
                        <th class="text-center">Estoque</th>
                        <th class="text-center">Disponível</th>
                        <th class="text-center">Remover</th>
                    </tr>
                </thead>
                <tbody id="tbody">
                    {% for item in lista_de_produtos %}
                        <tr>
                            <td width="10%" class="text-center">
                                {{ item.produto.id }}
                            </td>
                            <td width="35%">
                                {{ item.produto.nome }}
                            </td>
                            <td width="15%" class="text-center">
                                {{ item.produto.preco }}
                            </td>
                            <td width="15%" class="text-center">
                                <form style="width: 60px;" class="mx-auto" action ="{% url 'Site:atualiza_produto' %}" method ="POST" novalidate>
                                    {% csrf_token %}
                                    {{ item.form.estoque }}
                                </form>
                            </td>
                            <td width="15%" class="text-center">
                                {% if item.produto.disponivel %} Sim {% else %} Não {% endif %}
                            </td>
                            <td width="10%" class="text-center">
                                <form style="margin-bottom: 0px;"
                                      action ="{% url 'Site:remove_produto' %}"
                                      method ="post" novalidate>
                                    {% csrf_token %}
                                    <button style="margin-top: 0px; margin-bottom: 0px; padding-top: 3px; padding-bottom: 3px;"
                                            type="button" class="btn btn-sm btn-danger btn-remove" {% if item.produto.user != request.user %} disabled="disabled" {% endif %}>
                                        <img src="{% static 'produto/images/skin/database_delete.png' %}">
                                        Remover
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="5" width="90%" class="text-left">
                            <strong style="margin-left: 10px;">Total do estoque ...</strong>
                        </td>
                        <td width="10%" class="text-right">
                            <strong id="valor-do-estoque">{{ valor_do_estoque }}</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Trabalho_8_devWeb/templates/produto/valor_do_estoque.html
{% load filtros %}
{{ valor_do_estoque|separador_de_milhar }}