Trabalho_8_devWeb/Site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'Site'


urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('noticia/', views.noticia, name='noticia'),
    path('login/', views.login, name='login'),
    path('cadastrar/', views.cadastra_User, name='cadastra_User'),
    path('exibirUser/<int:id>/', views.exibe_user, name='exibe_user'),
    path('editar/<int:id>/', views.edita_user, name='edita_user'),
    path('remover/', views.remove_user, name='remove_user'),

    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('remove_produto/', views.remove_produto, name='remove_produto'),
    path('atualiza_produto/', views.atualiza_produto, name='atualiza_produto'),
    path('listar_produto/', views.lista_produtos, name='lista_produtos'),
    path('exibir/<int:id>/', views.exibe_produto, name='exibe_produto'),

    path('SalvaprodutoCarrinho/', views.SalvaprodutoCarrinho, name='SalvaprodutoCarrinho'),
    path('RemoveprodutoCarrinho/', views.RemoveprodutoCarrinho, name='RemoveprodutoCarrinho'),

    path('Carrinho/',views.ListaCarrinho,name='ListaCarrinho'),
]

Trabalho_8_devWeb/Trabalho_5_devWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Site.urls')),
    path('Site/', include('Site.urls')),
    path('autenticacao/', include('autenticacao.urls')),
]

Trabalho_8_devWeb/templates/Vendas/Lista_carrinho.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
    Carrinho
{% endblock %}

{% block conteudo %}
    <br>
    <div class="row">
        <div class="col-12">
            <h4 class="titulo mb-0">Carrinho</h4>
            <hr class="mt-2 mb-4">
        </div>
    </div>

    {% if lista_de_carrinhos %}
        <br>
        <div class="text-center"><h4>Lista de Produtos</h4></div>
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table style="width:100%" class="table table-striped table-sm table-bordered">
                        <thead>
                            <tr>
                                <th class="texto text-center">Categoria</th>
                                <th class="texto text-center">Nome</th>
                                <th class="texto text-center">Preço</th>
                                <th class="texto text-center">Cotas Atuais</th>
                                <th class="texto text-center">Cotas</th>
                                <th class="texto text-center">Remover</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for carrinho in lista_de_carrinhos %}
                                <tr>
                                    <td width="20%" class="text-left">
                                        <span class="texto">
                                            {{ carrinho.produto.categoria }}
                                        </span>
                                    </td>
                                    <td width="35%" class="text-left">
                                        <span class="texto">
                                            <a href="{% url 'Site:exibe_produto' carrinho.produto.id %}">{{ carrinho.produto.nome }}</a>
                                        </span>
                                    </td>
                                    <td width="15%" class="text-right">
                                        <span class="texto mr-4">
                                            {{ carrinho.preco }}
                                        </span>
                                    </td>
                                    <td width="15%" class="text-right">
                                        <span class="texto mr-4">
                                            {{ carrinho.cotas }}
                                        </span>
                                    </td>
                                     <td width="10%" class="text-center">
                                        <input type="text" class="form-control" id="produto_qtd" placeholder="cotas">

                                    </td>
                                    <td width="20%" class="text-center">
                                        <form style="margin-bottom: 0px;"
                                              action ="{% url 'Site:RemoveprodutoCarrinho' %}"
                                              method ="post" novalidate>
                                            {% csrf_token %}
                                            <button style="margin-top: 0px; margin-bottom: 0px; padding-top: 3px; padding-bottom: 3px;"
                                                    type="button" class="btn btn-sm btn-primary btn-removerProd" >
                                              Remover
                                            </button>

                                            <input type='hidden' name='produto_id' value='{{ carrinho.produto.id }}'>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% include 'Vendas/barra_de_paginacao.html' %}
    {% else %}

    {% endif %}


{% endblock %}

{% block domready %}


{% endblock %}

Trabalho_8_devWeb/templates/Vendas/barra_de_paginacao.html
<div class="row" style="font-size: 14px;">
    <div class="col-12">
        {% if produtos.has_other_pages %}
            <ul class="pagination">
                {% if produtos.has_previous %}
                    <li class="page-item"><a class="page-link" href="?pagina={{ produtos.previous_page_number }}&buscaPor={{ buscaPor }}">Anterior</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Anterior</a></li>
                {% endif %}
                {% for i in produtos.paginator.page_range %}
                    {% if produtos.number == i %}
                        <li class="page-item active"><a class="page-link" href="#">{{ i }} </a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?pagina={{ i }}&buscaPor={{ buscaPor }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if produtos.has_next %}
                    <li class="page-item"><a class="page-link" href="?pagina={{ produtos.next_page_number }}&buscaPor={{ buscaPor }}">Próxima</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Próxima</a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
</div>

Trabalho_8_devWeb/templates/Vendas/pesquisa_produto.html
{% extends "base.html" %}

{% load static %}

{% block titulo %}
   Compra de cotas de fundos
{% endblock %}

{% block conteudo %}
    <br>
    <div class="row">
        <div class="col-12">
            <h4 class="titulo mb-0">Compra de cotas de fundos</h4>
            <hr class="mt-2 mb-4">
        </div>
    </div>

    {% if lista_de_produtos %}
        <br>
        <div class="text-center"><h4>Lista de Produtos</h4></div>
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table style="width:100%" class="table table-striped table-sm table-bordered">
                        <thead>
                            <tr>
                                <th class="texto text-center">Categoria</th>
                                <th class="texto text-center">Nome</th>
                                <th class="texto text-center">Preço</th>
                                <th class="texto text-center">Cotas</th>
                                <th class="texto text-center">Comprar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for produto in lista_de_produtos %}
                                <tr>
                                    <td width="20%" class="text-left">
                                        <span class="texto">
                                            {{ produto.categoria }}
                                        </span>
                                    </td>
                                    <td width="35%" class="text-left">
                                        <span class="texto">
                                            <a href="{% url 'Site:exibe_produto' produto.id %}">{{ produto.nome }}</a>
                                        </span>
                                    </td>
                                    <td width="15%" class="text-right">
                                        <span class="texto mr-4">
                                            {{ produto.preco }}
                                        </span>
                                    </td>

                                     <td width="10%" class="text-center">
                                        <input type="text" class="form-control" id="produto_qtd" placeholder="cotas">

                                    </td>
                                    <td width="20%" class="text-center">
                                        <form style="margin-bottom: 0px;"
                                              action ="{% url 'Site:SalvaprodutoCarrinho' %}"
                                              method ="post" novalidate>
                                            {% csrf_token %}
                                            <button style="margin-top: 0px; margin-bottom: 0px; padding-top: 3px; padding-bottom: 3px;"
                                                    type="button" class="btn btn-sm btn-primary btn-comprar" >
                                              Comprar
                                            </button>

                                            <input type='hidden' name='produto_id' value='{{ produto.id }}'>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% include 'Vendas/barra_de_paginacao.html' %}
    {% endif %}

{% endblock %}

{% block domready %}


{% endblock %}